gerbv: src/export-image.c File Reference
export-image.c File Reference
libgerbv
Functions
void gerbv_export_png_file_from_project_autoscaled (gerbv_project_t *gerbvProject, int widthInPixels, int heightInPixels, const gchar *filename)
void gerbv_export_png_file_from_project (gerbv_project_t *gerbvProject, gerbv_render_info_t *renderInfo, const gchar *filename)
void gerbv_export_pdf_file_from_project_autoscaled (gerbv_project_t *gerbvProject, const gchar *filename)
void gerbv_export_pdf_file_from_project (gerbv_project_t *gerbvProject, gerbv_render_info_t *renderInfo, const gchar *filename)
void gerbv_export_postscript_file_from_project_autoscaled (gerbv_project_t *gerbvProject, const gchar *filename)
void gerbv_export_postscript_file_from_project (gerbv_project_t *gerbvProject, gerbv_render_info_t *renderInfo, const gchar *filename)
void gerbv_export_svg_file_from_project_autoscaled (gerbv_project_t *gerbvProject, const gchar *filename)
void gerbv_export_svg_file_from_project (gerbv_project_t *gerbvProject, gerbv_render_info_t *renderInfo, const gchar *filename)
Detailed Description
This file contains image exporting functions for exporting to PNG, PDF, SVG, and Postscript formats.
Definition in file export-image.c.
Function Documentation
gerbv_export_pdf_file_from_project()
void gerbv_export_pdf_file_from_project (gerbv_project_t * gerbvProject, gerbv_render_info_t * renderInfo, const gchar * filename)
Render a project to a PDF file using user-specified render info.
Parameters
gerbvProject the project to render
renderInfo the render settings for the rendered image
filename the filename for the exported PDF file
Definition at line 110 of file export-image.c.
References gerbv_render_info_t::displayHeight, and gerbv_render_info_t::displayWidth.
gerbv_export_pdf_file_from_project_autoscaled()
void gerbv_export_pdf_file_from_project_autoscaled (gerbv_project_t * gerbvProject, const gchar * filename)
Render a project to a PDF file, autoscaling the layers to fit inside the specified image dimensions.
Parameters
gerbvProject the project to render
filename the filename for the exported PDF file
Definition at line 104 of file export-image.c.
gerbv_export_png_file_from_project()
void gerbv_export_png_file_from_project (gerbv_project_t * gerbvProject, gerbv_render_info_t * renderInfo, const gchar * filename)
Render a project to a PNG file using user-specified render info.
Parameters
gerbvProject the project to render
renderInfo the render settings for the rendered image
filename the filename for the exported PNG file
Definition at line 89 of file export-image.c.
References gerbv_render_info_t::displayHeight, and gerbv_render_info_t::displayWidth.
Referenced by gerbv_export_png_file_from_project_autoscaled().
gerbv_export_png_file_from_project_autoscaled()
void gerbv_export_png_file_from_project_autoscaled (gerbv_project_t * gerbvProject, int widthInPixels, int heightInPixels, const gchar * filename)
Render a project to a PNG file, autoscaling the layers to fit inside the specified image dimensions.
Parameters
gerbvProject the project to render
widthInPixels the width of the rendered picture (in pixels)
heightInPixels the height of the rendered picture (in pixels)
filename the filename for the exported PNG file
Examples
example3.c.
Definition at line 77 of file export-image.c.
References gerbv_export_png_file_from_project(), GERBV_RENDER_TYPE_CAIRO_HIGH_QUALITY, and gerbv_render_zoom_to_fit_display().
gerbv_export_postscript_file_from_project()
void gerbv_export_postscript_file_from_project (gerbv_project_t * gerbvProject, gerbv_render_info_t * renderInfo, const gchar * filename)
Render a project to a Postscript file using user-specified render info.
Parameters
gerbvProject the project to render
renderInfo the render settings for the rendered image
filename the filename for the exported Postscript file
Definition at line 125 of file export-image.c.
References gerbv_render_info_t::displayHeight, and gerbv_render_info_t::displayWidth.
gerbv_export_postscript_file_from_project_autoscaled()
void gerbv_export_postscript_file_from_project_autoscaled (gerbv_project_t * gerbvProject, const gchar * filename)
Render a project to a Postscript file, autoscaling the layers to fit inside the specified image dimensions.
Parameters
gerbvProject the project to render
filename the filename for the exported Postscript file
Definition at line 119 of file export-image.c.
gerbv_export_svg_file_from_project()
void gerbv_export_svg_file_from_project (gerbv_project_t * gerbvProject, gerbv_render_info_t * renderInfo, const gchar * filename)
Render a project to a file using user-specified render info.
Parameters
gerbvProject the project to render
renderInfo the render settings for the rendered image
filename the filename for the exported file
Definition at line 139 of file export-image.c.
References gerbv_render_info_t::displayHeight, and gerbv_render_info_t::displayWidth.
gerbv_export_svg_file_from_project_autoscaled()
void gerbv_export_svg_file_from_project_autoscaled (gerbv_project_t * gerbvProject, const gchar * filename)
Render a project to a SVG file, autoscaling the layers to fit inside the specified image dimensions.
Parameters
gerbvProject the project to render
filename the filename for the exported file
Definition at line 133 of file export-image.c.