gerbv: src/gerber.h File Reference
gerber.h File Reference
libgerbv
Functions
gerbv_image_t * parse_gerb (gerb_file_t *fd, gchar *directoryPath)
gboolean gerber_is_rs274x_p (gerb_file_t *fd, gboolean *returnFoundBinary)
gboolean gerber_is_rs274d_p (gerb_file_t *fd)
const char * gerber_d_code_name (int d_code)
const char * gerber_g_code_name (int g_code)
const char * gerber_m_code_name (int m_code)
Detailed Description
Header info for the RS274X parsing functions.
Definition in file gerber.h.
Function Documentation
gerber_is_rs274d_p()
gboolean gerber_is_rs274d_p (gerb_file_t * fd)
Checks for signs that this is a RS-274D file Returns TRUE if it is, FALSE if not.
Definition at line 846 of file gerber.c.
gerber_is_rs274x_p()
gboolean gerber_is_rs274x_p (gerb_file_t * fd, gboolean * returnFoundBinary)
Checks for signs that this is a RS-274X file Returns TRUE if it is, FALSE if not.
Definition at line 756 of file gerber.c.
parse_gerb()
gerbv_image_t* parse_gerb (gerb_file_t * fd, gchar * directoryPath)
This is a wrapper which gets called from top level. It does some initialization and pre-processing, and then calls gerber_parse_file_segment which processes the actual file. Then it does final modifications to the image created.
Definition at line 692 of file gerber.c.
References gerber_parse_file_segment(), gerbv_create_image(), GERBV_LAYERTYPE_RS274X, gerbv_image_t::gerbv_stats, gerbv_stats_new(), gerbv_net::layer, gerbv_image_t::layers, gerbv_image_t::layertype, gerbv_image_t::netlist, gerbv_net::state, and gerbv_image_t::states.