gerbv: src/gerb_stats.c File Reference
gerb_stats.c File Reference
libgerbv
Functions
gerbv_stats_t * gerbv_stats_new (void)
void gerbv_stats_destroy (gerbv_stats_t *stats)
void gerbv_stats_add_layer (gerbv_stats_t *accum_stats, gerbv_stats_t *input_stats, int this_layer)
int gerbv_escape_char_return_int (char c)
Detailed Description
Statistics generating functions for RS274X files.
Definition in file gerb_stats.c.
Function Documentation
gerbv_escape_char_return_int()
int gerbv_escape_char_return_int (char c)
Escape special ASCII char ('
', '\0').
Return C string with escaped special char or original char in integer. Use gerbv_escape_char(char) macro instead of this function.
Definition at line 242 of file gerb_stats.c.
gerbv_stats_add_layer()
void gerbv_stats_add_layer (gerbv_stats_t * accum_stats, gerbv_stats_t * input_stats, int this_layer)
This fcn is called with a two gerbv_stats_t structs: accum_stats and input_stats. Accum_stats holds a list of stats accumulated for all layers. This will be reported in the report window. Input_stats holds a list of the stats for one particular layer to be added to the accumulated list.
Definition at line 121 of file gerb_stats.c.
Referenced by generate_gerber_analysis().
gerbv_stats_destroy()
void gerbv_stats_destroy (gerbv_stats_t * stats)
Free the memory for a stats struct
Definition at line 104 of file gerb_stats.c.
gerbv_stats_new()
gerbv_stats_t* gerbv_stats_new (void)
Allocates a new gerbv_stats structure.
Returns
gerbv_stats pointer on success, NULL on ERROR
Definition at line 46 of file gerb_stats.c.
Referenced by generate_gerber_analysis(), and parse_gerb().