gerbv: src/interface.c File Reference
interface.c File Reference
Gerbv
Functions
gboolean interface_get_alert_dialog_response (const gchar *primaryText, const gchar *secondaryText, gboolean show_checkbox, gboolean *ask_to_show_again, const gchar *true_button_label, const gchar *false_button_label)
int interface_reopen_question (GSList *fns, GSList *fns_is_mod, GSList *fns_cnt, GSList *fns_lay_num)
void interface_show_alert_dialog (gchar *primaryText, gchar *secondaryText, gboolean show_checkbox, gboolean *ask_to_show_again)
Detailed Description
GUI building functions for Gerbv.
Definition in file interface.c.
Function Documentation
interface_get_alert_dialog_response()
gboolean interface_get_alert_dialog_response (const gchar * primaryText, const gchar * secondaryText, gboolean show_checkbox, gboolean * ask_to_show_again, const gchar * true_button_label, const gchar * false_button_label)
This dialog box shows a message and two buttons: "True" and "False".
It returns gboolean 1 if the user clicked "True", and gboolean 0 if the user clicked "False".
Definition at line 1772 of file interface.c.
Referenced by callbacks_new_project_activate(), callbacks_quit_activate(), and open_project().
interface_show_alert_dialog()
void interface_show_alert_dialog (gchar * primaryText, gchar * secondaryText, gboolean show_checkbox, gboolean * ask_to_show_again)
This dialog box shows a textmessage and one button: "OK".
It does not return anything.
Definition at line 2093 of file interface.c.