gerbv: src/render.c File Reference
render.c File Reference
Gerbv
Functions
void render_calculate_zoom_from_outline (GtkWidget *widget, GdkEventButton *event)
void render_toggle_measure_line (void)
void render_draw_measure_distance (void)
gerbv_stats_t * generate_gerber_analysis (void)
gerbv_drill_stats_t * generate_drill_analysis (void)
Detailed Description
Rendering support functions for gerbv.
Definition in file render.c.
Function Documentation
generate_drill_analysis()
gerbv_drill_stats_t* generate_drill_analysis (void)
This fills out the project's Drill statistics table. It is called from within callbacks.c when the user asks for a Drill report.
Definition at line 640 of file render.c.
References gerbv_image_t::drill_stats, gerbv_project_t::file, gerbv_drill_stats_add_layer(), gerbv_drill_stats_new(), GERBV_LAYERTYPE_DRILL, gerbv_fileinfo_t::image, gerbv_fileinfo_t::isVisible, gerbv_project_t::last_loaded, gerbv_image_t::layertype, and mainProject.
Referenced by callbacks_analyze_active_drill_activate().
generate_gerber_analysis()
gerbv_stats_t* generate_gerber_analysis (void)
This fills out the project's Gerber statistics table. It is called from within callbacks.c when the user asks for a Gerber report.
Definition at line 615 of file render.c.
References gerbv_project_t::file, GERBV_LAYERTYPE_RS274X, gerbv_image_t::gerbv_stats, gerbv_stats_add_layer(), gerbv_stats_new(), gerbv_fileinfo_t::image, gerbv_fileinfo_t::isVisible, gerbv_project_t::last_loaded, gerbv_image_t::layertype, and mainProject.
Referenced by callbacks_analyze_active_gerbers_activate().
render_calculate_zoom_from_outline()
void render_calculate_zoom_from_outline (GtkWidget * widget, GdkEventButton * event)
Will determine the outline of the zoomed regions.
In case region to be zoomed is too small (which correspondes e.g. to a double click) it is interpreted as a right-click and will be used to identify a part from the CURRENT selection, which is drawn on screen
Definition at line 139 of file render.c.